// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Boards             string
	CardAttachments    string
	CardChecklistItems string
	CardComments       string
	CardLabels         string
	CardUsers          string
	Cards              string
	Columns            string
	Users              string
}{
	Boards:             "boards",
	CardAttachments:    "card_attachments",
	CardChecklistItems: "card_checklist_items",
	CardComments:       "card_comments",
	CardLabels:         "card_labels",
	CardUsers:          "card_users",
	Cards:              "cards",
	Columns:            "columns",
	Users:              "users",
}
