// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CardChecklistItem is an object representing the database table.
type CardChecklistItem struct {
	ID       int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Text     string `boil:"text" json:"text" toml:"text" yaml:"text"`
	Position int    `boil:"position" json:"position" toml:"position" yaml:"position"`
	CardID   int    `boil:"card_id" json:"card_id" toml:"card_id" yaml:"card_id"`

	R *cardChecklistItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L cardChecklistItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CardChecklistItemColumns = struct {
	ID       string
	Text     string
	Position string
	CardID   string
}{
	ID:       "id",
	Text:     "text",
	Position: "position",
	CardID:   "card_id",
}

var CardChecklistItemTableColumns = struct {
	ID       string
	Text     string
	Position string
	CardID   string
}{
	ID:       "card_checklist_items.id",
	Text:     "card_checklist_items.text",
	Position: "card_checklist_items.position",
	CardID:   "card_checklist_items.card_id",
}

// Generated where

var CardChecklistItemWhere = struct {
	ID       whereHelperint
	Text     whereHelperstring
	Position whereHelperint
	CardID   whereHelperint
}{
	ID:       whereHelperint{field: "`card_checklist_items`.`id`"},
	Text:     whereHelperstring{field: "`card_checklist_items`.`text`"},
	Position: whereHelperint{field: "`card_checklist_items`.`position`"},
	CardID:   whereHelperint{field: "`card_checklist_items`.`card_id`"},
}

// CardChecklistItemRels is where relationship names are stored.
var CardChecklistItemRels = struct {
	Card string
}{
	Card: "Card",
}

// cardChecklistItemR is where relationships are stored.
type cardChecklistItemR struct {
	Card *Card `boil:"Card" json:"Card" toml:"Card" yaml:"Card"`
}

// NewStruct creates a new relationship struct
func (*cardChecklistItemR) NewStruct() *cardChecklistItemR {
	return &cardChecklistItemR{}
}

func (r *cardChecklistItemR) GetCard() *Card {
	if r == nil {
		return nil
	}
	return r.Card
}

// cardChecklistItemL is where Load methods for each relationship are stored.
type cardChecklistItemL struct{}

var (
	cardChecklistItemAllColumns            = []string{"id", "text", "position", "card_id"}
	cardChecklistItemColumnsWithoutDefault = []string{"text", "position", "card_id"}
	cardChecklistItemColumnsWithDefault    = []string{"id"}
	cardChecklistItemPrimaryKeyColumns     = []string{"id"}
	cardChecklistItemGeneratedColumns      = []string{}
)

type (
	// CardChecklistItemSlice is an alias for a slice of pointers to CardChecklistItem.
	// This should almost always be used instead of []CardChecklistItem.
	CardChecklistItemSlice []*CardChecklistItem
	// CardChecklistItemHook is the signature for custom CardChecklistItem hook methods
	CardChecklistItemHook func(boil.Executor, *CardChecklistItem) error

	cardChecklistItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	cardChecklistItemType                 = reflect.TypeOf(&CardChecklistItem{})
	cardChecklistItemMapping              = queries.MakeStructMapping(cardChecklistItemType)
	cardChecklistItemPrimaryKeyMapping, _ = queries.BindMapping(cardChecklistItemType, cardChecklistItemMapping, cardChecklistItemPrimaryKeyColumns)
	cardChecklistItemInsertCacheMut       sync.RWMutex
	cardChecklistItemInsertCache          = make(map[string]insertCache)
	cardChecklistItemUpdateCacheMut       sync.RWMutex
	cardChecklistItemUpdateCache          = make(map[string]updateCache)
	cardChecklistItemUpsertCacheMut       sync.RWMutex
	cardChecklistItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var cardChecklistItemAfterSelectHooks []CardChecklistItemHook

var cardChecklistItemBeforeInsertHooks []CardChecklistItemHook
var cardChecklistItemAfterInsertHooks []CardChecklistItemHook

var cardChecklistItemBeforeUpdateHooks []CardChecklistItemHook
var cardChecklistItemAfterUpdateHooks []CardChecklistItemHook

var cardChecklistItemBeforeDeleteHooks []CardChecklistItemHook
var cardChecklistItemAfterDeleteHooks []CardChecklistItemHook

var cardChecklistItemBeforeUpsertHooks []CardChecklistItemHook
var cardChecklistItemAfterUpsertHooks []CardChecklistItemHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CardChecklistItem) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CardChecklistItem) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CardChecklistItem) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CardChecklistItem) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CardChecklistItem) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CardChecklistItem) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CardChecklistItem) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CardChecklistItem) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CardChecklistItem) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cardChecklistItemAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCardChecklistItemHook registers your hook function for all future operations.
func AddCardChecklistItemHook(hookPoint boil.HookPoint, cardChecklistItemHook CardChecklistItemHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		cardChecklistItemAfterSelectHooks = append(cardChecklistItemAfterSelectHooks, cardChecklistItemHook)
	case boil.BeforeInsertHook:
		cardChecklistItemBeforeInsertHooks = append(cardChecklistItemBeforeInsertHooks, cardChecklistItemHook)
	case boil.AfterInsertHook:
		cardChecklistItemAfterInsertHooks = append(cardChecklistItemAfterInsertHooks, cardChecklistItemHook)
	case boil.BeforeUpdateHook:
		cardChecklistItemBeforeUpdateHooks = append(cardChecklistItemBeforeUpdateHooks, cardChecklistItemHook)
	case boil.AfterUpdateHook:
		cardChecklistItemAfterUpdateHooks = append(cardChecklistItemAfterUpdateHooks, cardChecklistItemHook)
	case boil.BeforeDeleteHook:
		cardChecklistItemBeforeDeleteHooks = append(cardChecklistItemBeforeDeleteHooks, cardChecklistItemHook)
	case boil.AfterDeleteHook:
		cardChecklistItemAfterDeleteHooks = append(cardChecklistItemAfterDeleteHooks, cardChecklistItemHook)
	case boil.BeforeUpsertHook:
		cardChecklistItemBeforeUpsertHooks = append(cardChecklistItemBeforeUpsertHooks, cardChecklistItemHook)
	case boil.AfterUpsertHook:
		cardChecklistItemAfterUpsertHooks = append(cardChecklistItemAfterUpsertHooks, cardChecklistItemHook)
	}
}

// One returns a single cardChecklistItem record from the query.
func (q cardChecklistItemQuery) One(exec boil.Executor) (*CardChecklistItem, error) {
	o := &CardChecklistItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for card_checklist_items")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CardChecklistItem records from the query.
func (q cardChecklistItemQuery) All(exec boil.Executor) (CardChecklistItemSlice, error) {
	var o []*CardChecklistItem

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to CardChecklistItem slice")
	}

	if len(cardChecklistItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CardChecklistItem records in the query.
func (q cardChecklistItemQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count card_checklist_items rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q cardChecklistItemQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if card_checklist_items exists")
	}

	return count > 0, nil
}

// Card pointed to by the foreign key.
func (o *CardChecklistItem) Card(mods ...qm.QueryMod) cardQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CardID),
	}

	queryMods = append(queryMods, mods...)

	return Cards(queryMods...)
}

// LoadCard allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (cardChecklistItemL) LoadCard(e boil.Executor, singular bool, maybeCardChecklistItem interface{}, mods queries.Applicator) error {
	var slice []*CardChecklistItem
	var object *CardChecklistItem

	if singular {
		var ok bool
		object, ok = maybeCardChecklistItem.(*CardChecklistItem)
		if !ok {
			object = new(CardChecklistItem)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCardChecklistItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCardChecklistItem))
			}
		}
	} else {
		s, ok := maybeCardChecklistItem.(*[]*CardChecklistItem)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCardChecklistItem)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCardChecklistItem))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &cardChecklistItemR{}
		}
		args = append(args, object.CardID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &cardChecklistItemR{}
			}

			for _, a := range args {
				if a == obj.CardID {
					continue Outer
				}
			}

			args = append(args, obj.CardID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`cards`),
		qm.WhereIn(`cards.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Card")
	}

	var resultSlice []*Card
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Card")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for cards")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for cards")
	}

	if len(cardAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Card = foreign
		if foreign.R == nil {
			foreign.R = &cardR{}
		}
		foreign.R.CardChecklistItems = append(foreign.R.CardChecklistItems, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CardID == foreign.ID {
				local.R.Card = foreign
				if foreign.R == nil {
					foreign.R = &cardR{}
				}
				foreign.R.CardChecklistItems = append(foreign.R.CardChecklistItems, local)
				break
			}
		}
	}

	return nil
}

// SetCard of the cardChecklistItem to the related item.
// Sets o.R.Card to related.
// Adds o to related.R.CardChecklistItems.
func (o *CardChecklistItem) SetCard(exec boil.Executor, insert bool, related *Card) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `card_checklist_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"card_id"}),
		strmangle.WhereClause("`", "`", 0, cardChecklistItemPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CardID = related.ID
	if o.R == nil {
		o.R = &cardChecklistItemR{
			Card: related,
		}
	} else {
		o.R.Card = related
	}

	if related.R == nil {
		related.R = &cardR{
			CardChecklistItems: CardChecklistItemSlice{o},
		}
	} else {
		related.R.CardChecklistItems = append(related.R.CardChecklistItems, o)
	}

	return nil
}

// CardChecklistItems retrieves all the records using an executor.
func CardChecklistItems(mods ...qm.QueryMod) cardChecklistItemQuery {
	mods = append(mods, qm.From("`card_checklist_items`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`card_checklist_items`.*"})
	}

	return cardChecklistItemQuery{q}
}

// FindCardChecklistItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCardChecklistItem(exec boil.Executor, iD int, selectCols ...string) (*CardChecklistItem, error) {
	cardChecklistItemObj := &CardChecklistItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `card_checklist_items` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, cardChecklistItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from card_checklist_items")
	}

	if err = cardChecklistItemObj.doAfterSelectHooks(exec); err != nil {
		return cardChecklistItemObj, err
	}

	return cardChecklistItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CardChecklistItem) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no card_checklist_items provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cardChecklistItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	cardChecklistItemInsertCacheMut.RLock()
	cache, cached := cardChecklistItemInsertCache[key]
	cardChecklistItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			cardChecklistItemAllColumns,
			cardChecklistItemColumnsWithDefault,
			cardChecklistItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(cardChecklistItemType, cardChecklistItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(cardChecklistItemType, cardChecklistItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `card_checklist_items` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `card_checklist_items` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `card_checklist_items` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, cardChecklistItemPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into card_checklist_items")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == cardChecklistItemMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for card_checklist_items")
	}

CacheNoHooks:
	if !cached {
		cardChecklistItemInsertCacheMut.Lock()
		cardChecklistItemInsertCache[key] = cache
		cardChecklistItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the CardChecklistItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CardChecklistItem) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	cardChecklistItemUpdateCacheMut.RLock()
	cache, cached := cardChecklistItemUpdateCache[key]
	cardChecklistItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			cardChecklistItemAllColumns,
			cardChecklistItemPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update card_checklist_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `card_checklist_items` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, cardChecklistItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(cardChecklistItemType, cardChecklistItemMapping, append(wl, cardChecklistItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update card_checklist_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for card_checklist_items")
	}

	if !cached {
		cardChecklistItemUpdateCacheMut.Lock()
		cardChecklistItemUpdateCache[key] = cache
		cardChecklistItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q cardChecklistItemQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for card_checklist_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for card_checklist_items")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CardChecklistItemSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cardChecklistItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `card_checklist_items` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cardChecklistItemPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in cardChecklistItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all cardChecklistItem")
	}
	return rowsAff, nil
}

var mySQLCardChecklistItemUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CardChecklistItem) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no card_checklist_items provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cardChecklistItemColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLCardChecklistItemUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	cardChecklistItemUpsertCacheMut.RLock()
	cache, cached := cardChecklistItemUpsertCache[key]
	cardChecklistItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			cardChecklistItemAllColumns,
			cardChecklistItemColumnsWithDefault,
			cardChecklistItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			cardChecklistItemAllColumns,
			cardChecklistItemPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert card_checklist_items, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`card_checklist_items`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `card_checklist_items` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(cardChecklistItemType, cardChecklistItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(cardChecklistItemType, cardChecklistItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for card_checklist_items")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == cardChecklistItemMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(cardChecklistItemType, cardChecklistItemMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for card_checklist_items")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for card_checklist_items")
	}

CacheNoHooks:
	if !cached {
		cardChecklistItemUpsertCacheMut.Lock()
		cardChecklistItemUpsertCache[key] = cache
		cardChecklistItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single CardChecklistItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CardChecklistItem) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no CardChecklistItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cardChecklistItemPrimaryKeyMapping)
	sql := "DELETE FROM `card_checklist_items` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from card_checklist_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for card_checklist_items")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q cardChecklistItemQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no cardChecklistItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from card_checklist_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for card_checklist_items")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CardChecklistItemSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(cardChecklistItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cardChecklistItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `card_checklist_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cardChecklistItemPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cardChecklistItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for card_checklist_items")
	}

	if len(cardChecklistItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CardChecklistItem) Reload(exec boil.Executor) error {
	ret, err := FindCardChecklistItem(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CardChecklistItemSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CardChecklistItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cardChecklistItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `card_checklist_items`.* FROM `card_checklist_items` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cardChecklistItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CardChecklistItemSlice")
	}

	*o = slice

	return nil
}

// CardChecklistItemExists checks if the CardChecklistItem row exists.
func CardChecklistItemExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `card_checklist_items` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if card_checklist_items exists")
	}

	return exists, nil
}

// Exists checks if the CardChecklistItem row exists.
func (o *CardChecklistItem) Exists(exec boil.Executor) (bool, error) {
	return CardChecklistItemExists(exec, o.ID)
}
